name: Build and push image to repository
on:
  push:
    branches:
      - master
    paths:
      - release.sh
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Authenticate with registry
        run: docker login docker.pkg.github.com -u "Evonder" -p "${{ secrets.DOCKER_PASS }}"

      - name: Build the image
        run: docker build . -t packager

      - name: Push the latest tag
        run: |
          docker tag packager docker.pkg.github.com/evonder/packager/packager:latest
          docker push docker.pkg.github.com/evonder/packager/packager:latest

      - name: Push the nightly tag
        run: |
          TAG="$(date -u +%Y%m%d%H%M%S)"
          docker tag packager docker.pkg.github.com/evonder/packager/packager:$TAG
          docker push docker.pkg.github.com/evonder/packager/packager:$TAG
